package Repetition.NestedExceptions;

public class NumberValidatorException extends Exception{

    public NumberValidatorException(String message, Throwable cause) {
        super(message, cause);
    }
}
